### ISSUE TITLE
Implement Kapitan Embedded Secret Refs

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#111]
Kapitan added support for embedding secret refs directly into the secret object: https://github.com/deepmind/kapitan/pull/502

By using this approach we can get rid of the separate `refs/` directory and its files. Instead of writing the refs to these separate files they can be directly updated in the `secret.yaml` manifest.

Also see https://kapitan.dev/secrets/#5-compile-refs-in-embedded-format

**Comment by tobru** [comment]
We don't gain anything, so we opted to close that one.
