### ISSUE TITLE
Deduplicate logic in cookiecutter template and new-component wrapper

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/commodore#119]
As pointed out in https://github.com/projectsyn/commodore/pull/117#discussion_r442261806, we do have duplicated logic in the Cookiecutter template and the `new-component` wrapper.

@simu suggested to render the template first into a temporary folder. Then we can use the result object of `cookiecutter()` to get the rendered context variables and thus remove the duplicated logic.

**Comment by srueg** [comment]
Fixed in https://github.com/projectsyn/commodore/pull/133
