### ISSUE TITLE
Automated catalog update commit message is formatted incorrectly

### ISSUE THREAD

**Issue by mhutter** [projectsyn/commodore#136]
When looking at the commit history for a cluster catalog in GitLab, the commit title is empty (which leads to some usability issues with GitLab).

![image](https://user-images.githubusercontent.com/346819/86788464-7d52d880-c066-11ea-9710-0476b00f3a25.png)

## Steps to Reproduce the Problem

  1. check existing catalogs

## Actual Behavior
Commit title is empty

## Expected Behavior
Commit has a proper title

**Comment by mhutter** [comment]
My first instinct was that the commit message is not formatted correctly; however investigations showed that the commit messages are formatted correctly.

A test also showed that the issue cannot be reproduced on GitHub, so I assume this is a GitLab issue after all.

I'll try to reproduce the issue

**Comment by mhutter** [comment]
Related: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/62905

**Comment by mhutter** [comment]
The commit message does indeed contain a leading newline: https://github.com/projectsyn/commodore/blob/9a498fa819721d7f584a3f2e394718d11ecef01b/commodore/catalog.py#L41-L51

I assume the git cli and GitHub just trim that away; either during display or during commit. I try to reproduce the issue and report it to GitLab.

**Comment by mhutter** [comment]
@simu since this will be forever until it is fixed in GitLab, should we in the mean time fix this in commodore?

**Comment by srueg** [comment]
Nice catch, I tried to find the cause for this issue multiple times as well but wasn't successful! :tada:

**Comment by srueg** [comment]
I vote for "fixing" this in commodore, PR welcome :wink:

**Comment by mhutter** [comment]
I think this is within my Python knowledge
