### ISSUE TITLE
Research Implementation of Kapitan Remote Inventory

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#142]
## Context

with https://github.com/deepmind/kapitan/pull/521/files Kapitan supports the concept of [remote inventories](https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_7_remote_inventory.md). This could replace some of the logic we implemented in Commodore with Kapitan native features.

Research how we could make use of this new feature and implement it.

## Alternatives

We currently implement the alternative, which is preparing the inventory (cloning all parts) in Commodore before running Kapitan.

**Comment by tobru** [comment]
It's not something we need at this time, therefore we'll close it.
