### ISSUE TITLE
Rework Component Discovery

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#170]
## Context

Component discovery is currently based on the concept of searching the component under `COMMODORE_GLOBAL_GIT_BASE` or by checking a `commodore.yml` in the commodore-defaults Git repo. The idea is to get rid of that and store this information in Lieutenant.

Details still tbd.

**Comment by corvus-ch** [comment]
Quick fix could be to just configure the git base on the API side and retrieve it from there.

**Comment by corvus-ch** [comment]
With #247, component discovery got dropped. All required components now have to be listed explicitly. This makes this issue obsolete.
