### ISSUE TITLE
Location of global-common Git repo configurable

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#171]
## Context

Make the global common config Git repo location configurable via Lieutenant API. Get rid of COMMODORE_GLOBAL_GIT_BASE. Goes hand in hand with #170

**Comment by corvus-ch** [comment]
With #198 done, `COMMODORE_GLOBAL_GIT_BASE` is now only used as a fallback (maintain compatibility to older versions Lieutenant API). It is still in use to auto discover components not explicitly listed in `commodore.yml` within the global config git repo.

**Comment by corvus-ch** [comment]
Having this discussed with @simu, we concluded to just drop auto discovery for now. As a consequence, each and every component must be listed in `commodore.yml` within the global config git repo.

**Comment by corvus-ch** [comment]
I have extracted the drop part to #229. @tobru do you agree to close this one.
