### ISSUE TITLE
Engineer Automated Component Testing

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#172]
## Context

Implement a GitHub action to automatically test Commodore Components. For an initial testing it could look like this:

1. Render component locally
2. Run `kubeval` over the rendered manifests

Integrate this into the Cookiecutter template.

**Comment by corvus-ch** [comment]
As a result of this we should have a working example for component testing. That example should showcase:

- GitHub action workflow that renders the component
- Showcase how to assert things in the rendered output.

**Comment by ccremer** [comment]
I thought about Kubeval. The problem is the missing CRD support. We could practically not validate any manifests that are unknown to upstream Kubernetes. Maybe there's limited Openshift support.

WDYT about a similar approach as in https://github.com/appuio/charts/tree/master/k8up/test, where each Chart is unit tested with Go and the K8s API? We can do whitebox testing and actually assert whether the correct values are provided semantically. With Kubeval we can't check whether any composed values make sense, only whether they're syntactically correct. Also, importing the 3rd-party APIs allows us to test also generated manifests from CRDs.

I'll come up with something, that should allow us to discuss on better grounds.

**Comment by ccremer** [comment]
See https://github.com/projectsyn/component-espejo/pull/7 (all WIP atm):

```console
$ docker run --rm --user="1000" --volume "/home/chris/Documents/source/projectsyn/commodore/dependencies/espejo/../../:/app/data" --workdir /app/data projectsyn/commodore:latest component compile dependencies/espejo
Agent pid 11
grep: /app/.ssh: No such file or directory
No SSH keys were added
Compile component espejo...
Updating Jsonnet libraries...
Compiling catalog...
Dependency https://github.com/vshn/espejo/releases/download/v0.3.1/espejo-crd.yaml: fetching now
Dependency https://github.com/vshn/espejo/releases/download/v0.3.1/espejo-crd.yaml: successfully fetched
Not updating /app/data/dependencies/espejo/manifests/v0.3.1/crds/espejo-crd.yaml (file already exists)
Dependency https://github.com/vshn/espejo/releases/download/v0.3.1/espejo-crd.yaml: saved to /app/data/dependencies/espejo/manifests/v0.3.1/crds/espejo-crd.yaml
Compiled test (0.16s)
 > Component compiled to /app/data/compiled/test
Postprocessing...
$ cd tests && go test ./...
ok  	github.com/projectsyn/component-espejo	(cached)
```

**Comment by corvus-ch** [comment]
I do also see the limitations of Kubeval. Being able to tell if a yaml file contains valid Kubernetes objects is only half of the story. Doing assertions on individual values is the way to go. I like the approach with go tests but this might be on the reinventing the wheel side. I also fear that this approach will come with a lot of boiler plate code and or us ending up writing a framework. Have a look at https://learnk8s.io/validating-kubernetes-yaml. Config-lint and Conftest are intriguing me the most.

**Comment by srueg** [comment]
Nice work!

I think this could be a multi-layer solution:

1. Run Kubeval (with `--strict --ignore-missing-schemas`) to catch the core K8s types
1. Run something like [Conftest](https://www.conftest.dev/) for the structural tests (maybe even against [shared policies](https://www.conftest.dev/sharing/))
1. If necessary, provide tooling to write Go tests (I think a helper library could get rid of most of the boilerplate). The big benefit of this being the possibility to verify custom CRDs (by importing their struct and unmarshaling)

**Comment by srueg** [comment]
I also very much like Conftest since it's using the Rego syntax which we sooner or later probably will use for the [OPA](https://www.openpolicyagent.org/docs/latest/). And it allows to share policies so we could enforce them at various levels (e.g. each component & on a whole catalog).

**Comment by ccremer** [comment]
The current boilerplate code for go unit testing is about 15 lines. Yes, a library would be the way to go, but shouldn't be much to maintain.

I have searched for another tool to validate K8s manifests without the Go libraries, but didn't find any. Thanks @corvus-ch for the blog, I'll try several approaches so we can compare them.

**Comment by ccremer** [comment]
>     3. If necessary, provide tooling to write Go tests (I think a helper library could get rid of most of the boilerplate). The big benefit of this being the possibility to verify custom CRDs (by importing their struct and unmarshaling)

With Rego/conftest this is not necessary. In Rego, any CRDs is just plain data structure. However, out of the box with Rego we cannot validate certain data types (e.g. whether CPU request of `30Mi` makes sense. Only when we check for equality)

**Comment by corvus-ch** [comment]
We need to keep in mind what we need to test. The scope is a singe component. As a component author, I want to ensure that parameter values show up at the correct location within the output. If they have the correct type like `Mi` or `i` is not so much of interest. Reason for that being the fact, they are parameters and as such can be altered outside of our influence.

Just from reading documentations, it is hard to tell which approach would be the best. I can imaging to have and allow for multiple. The more important thing for now is: we need a working example of a GitHub action. Then we can start writing tests for the real life.

Adding another test framework or dropping one is then easy to do.

**Comment by corvus-ch** [comment]
And here is another one: https://github.com/stackrox/kube-linter. Might be too early to be usable but worth to keep an eye on.

**Comment by corvus-ch** [comment]
Having a look at those Golang tests in projectsyn/component-espejo/pull/8 makes me thinking. Where/when should the `component compile` be execute. When writing tests, we aim for small and isolated tests. With the `component compile` being executed before the go tests are run, we can only assert one outcome. What if we need to test more that one set of parameters? To a certain degree, this also applies to Conftest.

For the later, I would pair the `component compile` with the conftest call within the Makefile.

For the Golang tests, I would write the values files within the test and call `component compile` from within the test. I once have done something similar https://github.com/corvus-ch/rabbitmq-cli-consumer/blob/master/integration_test.go (probably not the simplest example).

**Comment by srueg** [comment]
Good point. This would also more closely resemble how we do Helm tests with Go: https://github.com/appuio/charts/blob/master/stardog/test/pull_secret_test.go#L26

I guess this is another reason to write a Go library for component testing.

**Comment by ccremer** [comment]
So, in the mid-term, following needs to be done:
* Setup Go-library for our testing helpers. Or contribute to https://github.com/gruntwork-io/terratest ?
* Engineer possibility to run different tests with different input parameters. Needs component compilation before each test
* Figure out how to run a common set of Rego policies against all component artifacts and how to manage them.

**Comment by tobru** [comment]
To finish this issue I'd propose to document the outcome of this research in an SDD: projectsyn/documentation#113 and finish it in the SDD. After the SDD has been agreed upon we can actually implement it. WDYT?

**Comment by ccremer** [comment]
See https://github.com/projectsyn/documentation/pull/117
