### ISSUE TITLE
Investigate Kapitan Upgrade Issues

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#203]
We tried to upgrade the Kapitan dependency to [v0.29.2](https://github.com/deepmind/kapitan/releases/tag/v0.29.2) which lead to various issues:
* On macOS we run into the `fatal: morestack g0` problem which we didn't before (see https://github.com/deepmind/kapitan/pull/568)
* Jsonnet compilation fails with `RUNTIME ERROR: Builtin function objectHasEx expected (object, string, boolean) but got (string, string, boolean)`
* A URI is added to the AlertManager config: `\"uri\": \"yaml_fs:///app/data/inventory/classes/global/commodore.yml\"\`

## Steps to Reproduce the Problem

  1. `poetry update`
  1. `poetry install`
  1. `poetry run commodore catalog compile c-old-fire-5788` (for the Jsonnet error)
  1. `poetry run commodore catalog compile c-4h8tcd` (on macOS for morestack error)
  1. `docker-compose run commodore catalog compile c-4h8tcd` (for the uri issue)

## Actual Behavior
As described above

## Expected Behavior
The cluster compiles should succeed and show no diffs compared to a compile with Kapitan v0.29.1

**Comment by srueg** [comment]
Might be related to the `uri` issue: https://github.com/kapicorp/reclass/pull/2/files#diff-985f50ddcf026e7418d954debc4544a6R191

**Comment by simu** [comment]
Maybe a fix https://github.com/kapicorp/reclass/pull/3

**Comment by simu** [comment]
Created a PR for Kapitan to update reclass: https://github.com/deepmind/kapitan/pull/632

**Comment by srueg** [comment]
Interestingly I get the `fatal: morestack on g0` error on macOS consistently on every run since #227. Even when setting the Kapitan `parallel` config to `1`.
