### ISSUE TITLE
Specify Jsonnet-Bundler Dependency Versions in Hierarchy

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#213]
## Context
Currently a component can have a `jsonnetfile.json` to specify Jsonnet dependencies. This file is not handled by Kapitan and therefore can't make use of the configuration hierarchy. The only way to have different versions of dependencies is with a separate branch of the component (which then can be specified in the hierarchy).

Implement a possibility to specify Jsonnet dependencies and their version in the hierarchy so they can be overridden.

For example the [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/) library is specific to the K8s version and therefore needs a different version (git branch/commit) for each K8s version.

## Alternatives
As described, an alternative would be to use different branches to handle this.

**Comment by srueg** [comment]
A possible solution could be to generate the `jsonnetfile.json` in Commodore and use input form the hierarchy to do so.

**Comment by srueg** [comment]
Implementation might affect #216

**Comment by corvus-ch** [comment]
This might also affect #173
