### ISSUE TITLE
Drop COMMODORE_GLOBAL_GIT_BASE

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/commodore#229]
## Context

The variable COMMODORE_GLOBAL_GIT_BASE is no longer used to determine the location of the global config git repository (See #226). However it is still in use for auto discovering component repositories.

Having this discussed this with @simu, we concluded to just drop auto discovery for now. As a consequence, each and every component must be listed in `commodore.yml` within the global config git repo.

Note that the global git base is for now still used for backwards comparability. Commodore is using it when talking to older versions of Lieutenant not providing the URL of the global config git repo.

## Alternatives

Make Lieutenant to provide the value needed for component auto discovery. Change Commodore to make use of that.

**Comment by mhutter** [comment]
+1 for removing autodiscovery, it makes it much more explicit to figure out where stuff comes from.
