### ISSUE TITLE
Unify how component URLs are defined

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/commodore#254]
## Context

#247 dropped auto discover of components. This makes it mandatory to have all required components listed in `commodore.yml` (name and URL). It is also possible to define component URLs within the hierarchy. This duplication should be removed. We should have only one place to have those URLs defined/configured.

**Comment by simu** [comment]
We cannot remove the option in the hierarchy (in `parameters`) as that allows switching to a different fork of a component for a subset of tenants/clusters.

Therefore we need to verify if we can use the configuration in `parameters` also for the initial component URLs (in `commodore.yml`). As far as I can see this should work without any issues as we are able to render the inventory for the bootstrap target before fetching the components.
