### ISSUE TITLE
Alias-only Instances Not Working as Intended

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#268]
## Steps to Reproduce the Problem

1. Use a component only with aliases:
  ```yaml
  applications:
    - service-broker as redis
    - service-broker as mariadb
  ```
  2. Compile catalog

## Actual Behavior
The component `service-broker` will be instantiated 3 times with the following names: `redis`, `mariadb` and `service-broker`.

## Expected Behavior
The component should only be instantiated 2 times, with the names `redis` and `mariadb`.

The problematic code is here: https://github.com/projectsyn/commodore/blob/master/commodore/dependency_mgmt.py#L75
and here: https://github.com/projectsyn/commodore/blob/master/commodore/compile.py#L73

Because we add the component to the `components` set and create a target for each component in there, the component will always be instantiated unaliased in addition to all aliased occurrences.

**Comment by simu** [comment]
Potential solution: create "fake" aliases for unaliased components, using the component name as the alias name, and don't render targets for components themselves anymore.
