### ISSUE TITLE
Version usage reporting for Commodore

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#293]
## Context

Currently we need to guess if the majority of the user base has upgraded to a Commodore version which supports new features, and have no real information about which versions are still in use.

In order to be able to identify features which can safely be removed and to have an idea of how quickly new Commodore versions are adopted by users, we'd like to have some kind of version usage reporting from Commodore.

## Potential approaches

This could be done in many different ways, so far the following have been suggested:
* Add an endpoint to the Lieutenant API to collect Commodore usage information
* Set a custom user-agent in Commodore and collect user-agent information from the Lieutenant API

**Comment by srueg** [comment]
Going the route with user agent could still be used if we drop the lieutenant-api (ref https://github.com/projectsyn/lieutenant-api/issues/94). We could then use Kubernetes audit logs which record the user agent of each API call.
