### ISSUE TITLE
Support for Kadet as Templating Engine

### ISSUE THREAD

**Issue by tobru** [projectsyn/commodore#296]
## Context

Commodore Components usually are written in Jsonnet and / or make use of Helm Charts. Kapitan also provides a templating language called [Kadet](https://github.com/kapicorp/kadet) which is much easier to grasp than Jsonnet. This might lower the entry barrier to write Commodore Components

We should figure out if and how we should support Kadet in Commodore. This would mean for example to add documentation, add it to the `component new` command to have an example and probably more.

## Alternatives

Theoretically it's already possible today to use Kadet by simply configuring it accordingly in the `<component>.yml` config (`input_type: kadet`). So we would not need to do anything more to support it.

**Comment by simu** [comment]
To consider: currently the Commodore postprocessing only supports Jsonnet, it might be interesting to have Kadet as an option for postprocessing filters.

**Comment by tobru** [comment]
There is no real need around, closing.
