### ISSUE TITLE
Add support for using `kustomize` in components

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#504]
## Context

We've written a bunch of components where we manually download upstream manifests which are intended to be rendered with kustomize, e.g. https://github.com/projectsyn/component-kyverno/. By having to download and render all manifests individually instead of being able to leverage kustomize, errors can happen, e.g. https://github.com/projectsyn/component-kyverno/pull/46

There's already a draft PR to add `kustomize` to the Commodore container image: #430

Additionally, we'll want at least basic documentation showing how to call kustomize from a component. We may be able to use Kapitan's [external input type](https://kapitan.dev/compile/#external-alphaexperimental) to run kustomize. This will require the standalone `kustomize` binary to be present in the path when Commodore is running.

## Alternatives

* Continue downloading kustomize manifests and patching them in Jsonnet

**Comment by bastjan** [comment]
Kustomize is used in here to render a controller runtime manifest: 
https://github.com/appuio/component-openshift4-slos/blob/6c201604813c1c6e8c55437cb451edea87ce0992/class/openshift4-slos.yml#L9-L29
