### ISSUE TITLE
Jsonnet dependency update is not deterministic

### ISSUE THREAD

**Issue by bastjan** [projectsyn/commodore#526]
Jsonnet bundler does not update (`jb install` without lockfile, `jb update`) dependencies deterministically. See https://github.com/jsonnet-bundler/jsonnet-bundler/issues/160

This leads to flaky commodore outputs.

## Steps to Reproduce the Problem

  1. Add [projectsyn/component-thanos](https://github.com/projectsyn/component-thanos) and [projectsyn/component-prometheus](https://github.com/projectsyn/component-prometheus)
  2. Compile a few times

## Actual Behavior

The output changes even though the dependencies do not.

## Expected Behavior

The output stays stable until a dependency is updated.

**Comment by simu** [comment]
This is fixed in https://github.com/projectsyn/jsonnet-bundler v0.6.0 and newer. The Commodore v1.19.1 container image uses our fork of jsonnet-bundler. Closing this issue.
