### ISSUE TITLE
--local is not useful if new components are added to the catalog

### ISSUE THREAD

**Issue by davidgubler** [projectsyn/commodore#590]
When adding a new component to the catalog (new entry under "applications:") it would be obvious to the user to test this with the --local flag and check the resulting yaml files.

The documentation (https://syn.tools/syn/how-tos/change-parameter.html) also says:
"You can compile the catalog locally to verify your changes with commodore catalog compile $CLUSTER_ID --local."
Which basically tells the user that "--local" is intended for this use case.

However, when doing so the compiled catalog does *not* contain the component that has just been added. There is no message or note in the documentation either alerting the user to this problem.

## Steps to Reproduce the Problem

  1. Compile existing inventory to a catalog
  1. Add a previously unused component to "applications:"
  1. Re-compile catalog using "--local" flag

## Actual Behavior
Resulting catalog does not change.

## Expected Behavior
Resulting catalog contains added component.

**Comment by simu** [comment]
We've moved the existing documentation explaining how you can test components with `catalog compile --local` into a how-to (https://syn.tools/commodore/how-to/local-mode-component.html), and the how-to is also linked in https://syn.tools/syn/how-tos/change-parameter.html.
