### ISSUE TITLE
Catalog compile quietly overwrites local changes

### ISSUE THREAD

**Issue by davidgubler** [projectsyn/commodore#591]
A normal catalog compile quietly overwrites local changes. This is especially annoying because it is easy to accidentally use "--push" instead of "--local" when compiling, and "--push" will overwrite the changes while "--local" won't.

Either the catalog compile should use the uncommited changes (which may be undesirable because that could result in a pushed catalog that contains changes that aren't present in the inventory repos) or it should stop with an error message explaining the problem.

## Steps to Reproduce the Problem

  1. Compile catalog using "commodore catalog compile ..."
  1. Change something in an inventory repo without commiting/pushing it
  1. Re-compile catalog using the same commodore command

## Actual Behavior
Commodore quietly reverts the changes done in the second step.

## Expected Behavior
Commodore either compiles a catalog including those changes or aborts with an error message.

**Comment by simu** [comment]
A potential approach to address this issue could be to introduce a new flag `--force`. Without this flag, catalog compilation would abort when `--local` isn't given and the working directory has uncommitted changes.

What's clearly a non-goal is to allow Commodore to push a catalog which was rendered from a working directory which had uncommitted changes.

Side-note: it probably also makes sense to abort compilation when there's committed but not pushed changes in the tenant or global repo unless we switch those repos to persist across compiles similar to what we've implemented for packages.
