### ISSUE TITLE
Sort the output of 'commodore catalog list'

### ISSUE THREAD

**Issue by ccremer** [projectsyn/commodore#596]
## Context

When issuing `commodore catalog list` we get a large list of cluster IDs.
Sort them alphabetically by name by default.

## Alternatives

* `commodore catalog list | sort` but then we don't see the displayname
* `commodore catalog list -v | sort` but it contains debug messages.

**Comment by glrf** [comment]
The output is now sorted by cluster ID in the backend by default. We'll improve the general UX of `commodore catalog list` in https://github.com/projectsyn/commodore/pull/671
