### ISSUE TITLE
Implement Option to Disable Components

### ISSUE THREAD

**Issue by srueg** [projectsyn/commodore#71]
It should be possible to disable a component which was included in the hierarchy. This helps for example for local testing.
The list of components do be disabled must be defined on the cluster and if possible anywhere in the hierarch. So for example a `local` cloud region could be implemented which disables most of the components.

## Task Deliverables

- [ ] List of components to be disabled can be specified on a cluster config
- [ ] If possible the list should be specified anywhere in the hierarchy

**Comment by simu** [comment]
Could become possible as part of the effort happening for #223, if we're switching to using the reclass `applications` field for component includes. Note there's currently a potential bug in reclass preventing removal of entries in `applications` from working as documented, cf. https://github.com/projectsyn/commodore/issues/223#issuecomment-712954065

**Comment by simu** [comment]
With #223  implemented using the `applications` array, and Kapitan updated to v0.29.4, we now support disabling components in parts of the hierarhcy by prefixing them with `~`. Note that this works only to disable components which were included higher up in the hierarchy.
