### ISSUE TITLE
Support jsonnet-bundler to manage component jsonnet dependencies

### ISSUE THREAD

**Issue by simu** [projectsyn/commodore#77]
Currently, the mechanisms available in Commodore don't really support pulling in jsonnet dependencies which use [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler).

However, many useful jsonnet libraries (e.g. [kube-prometheus](https://github.com/coreos/kube-prometheus)) make use of jsonnet-bundler. It's nearly impossible to include such a library in a Commodore component at the moment, or pull it in via the `jsonnet_libs` configuration which Commodore supports for 3rd party jsonnet libraries.

### Task deliverables
- [ ] Commodore supports pulling in jsonnet-bundler dependencies at the component level at compile time
- [ ] Commodore supports pulling in jsonnet-bundler dependencies at the global level at compile time

**Comment by corvus-ch** [comment]
Kapitan suggests to externalize resolution of dependencies and use the `--include-paths` option (https://github.com/deepmind/kapitan/pull/133). Jsonnet-bundler fits well into that premise.

Jsonnet-bundler allows to define dependencies of type `local`. Using this, we can define each and every folder (first level) within `dependencies` as a local Jsonnet dependency. We also need to add `vendor` to the include paths of Kapitan. Doing so will:

* link that component into `vendor`
* resolve and install component dependencies (component has a `jsonnetfile.json` at its root dir).

For this to work, commodore needs to to the following tasks:

* discover and download all components (implemented)
* create a `jsonnetfile.json` defining each and every folder within `dependencies` as a local Jsonnet dependency
* also add commodore and kube-libsonnet as dependency to `jsonnetfile.json`
* call `jb install`

Once we have done that, we have the opportunity to clean up commodore. With the above change, libraries of Commodore components will now be available at `<component name>/lib/<file name>`. This will allow us to remove all code responsible for linking those files into the `dependencies/lib` and `dependencies/libs` (follow up ticket). Given we have refactored all the existing components.
